In [ ]:
#!pip install meetup.api

In [3]:
import meetup.api
import json 
import requests 
import time 
import codecs
import sys
import io
import re
import pandas as pd
import sqlalchemy as sa

In [30]:
def superFetch(groupname, key):
    print("Start fetching...")
    client = meetup.api.Client(key)
    print('request status:',end=' ')
    group = client.GetGroup({'urlname':groupname})
    gid = group.id
    total = group.members
    want = 'id,name,state,city,lon,lat'
    limit = 200
    request = total//limit+1
    offsetValue = 0
    name = []
    uid = []
    state = []
    city = []
    lon = []
    lat = []
    for i in range(request):
        print('progress: ',offsetValue+1,'/',request, sep='')
        print('request status:',end=' ')
        try:
            members = client.GetMembers(group_id=gid, only=want,page=limit,offset=offsetValue)
            offsetValue+=1
            rList= members.results
            for j in rList:
                if len(j.keys())==4:
                    name.append(j['name'])
                    uid.append(j['id'])
                    state.append(j['state'])
                    city.append(j['city'])
                else:
                    uid.append(j['id'])
                    try:
                        name.append(j['name'])
                    except KeyError:
                        name.append('null')
                    try:
                        state.append(j['state'])
                    except KeyError:
                        state.append('null')
                    try:
                        city.append(j['city'])
                    except:
                        city.append('null')
                    try:
                        lon.append(j['lon'])
                        lat.append(j['lat'])
                    except:
                        lon.append('null')
                        lat.append('null')
        except json.decoder.JSONDecodeError:
            print("JSONDecodeError")
    print("fetching complete")
    df = pd.DataFrame({"name":name, "uid":uid, "state":state, "city":city, "lon":lon, "lat":lat})
    return df


key = '1a60703a102a6252424875415c1b21'
df = superFetch('DC-Tech-Meetup', key)

Start fetching...
request status: 29/30 (10 seconds remaining)
progress: 1/125
request status: 28/30 (10 seconds remaining)
progress: 2/125
request status: 27/30 (2 seconds remaining)
progress: 3/125
request status: 29/30 (10 seconds remaining)
progress: 4/125
request status: 28/30 (3 seconds remaining)
progress: 5/125
request status: 29/30 (10 seconds remaining)
progress: 6/125
request status: 28/30 (2 seconds remaining)
progress: 7/125
request status: 29/30 (10 seconds remaining)
progress: 8/125
request status: 28/30 (7 seconds remaining)
progress: 9/125
request status: 27/30 (4 seconds remaining)
progress: 10/125
request status: 26/30 (1 seconds remaining)
progress: 11/125
request status: 29/30 (10 seconds remaining)
progress: 12/125
request status: 28/30 (7 seconds remaining)
progress: 13/125
request status: 27/30 (4 seconds remaining)
progress: 14/125
request status: 29/30 (10 seconds remaining)
progress: 15/125
request status: 28/30 (7 seconds remaining)
progress: 16/125
request status: 27/30 (4 seconds remaining)
progress: 17/125
request status: 26/30 (1 seconds remaining)
progress: 18/125
request status: 29/30 (10 seconds remaining)
progress: 19/125
request status: 28/30 (7 seconds remaining)
progress: 20/125
request status: 27/30 (5 seconds remaining)
progress: 21/125
request status: 26/30 (2 seconds remaining)
progress: 22/125
request status: 29/30 (10 seconds remaining)
progress: 23/125
request status: 28/30 (7 seconds remaining)
progress: 24/125
request status: 27/30 (4 seconds remaining)
progress: 25/125
request status: 26/30 (1 seconds remaining)
progress: 26/125
request status: 29/30 (10 seconds remaining)
progress: 27/125
request status: 28/30 (6 seconds remaining)
progress: 28/125
request status: 27/30 (3 seconds remaining)
progress: 29/125
request status: 29/30 (10 seconds remaining)
progress: 30/125
request status: 28/30 (7 seconds remaining)
progress: 31/125
request status: 27/30 (4 seconds remaining)
progress: 32/125
request status: 26/30 (1 seconds remaining)
progress: 33/125
request status: 29/30 (10 seconds remaining)
progress: 34/125
request status: 28/30 (7 seconds remaining)
progress: 35/125
request status: 27/30 (4 seconds remaining)
progress: 36/125
request status: 26/30 (1 seconds remaining)
progress: 37/125
request status: 29/30 (10 seconds remaining)
progress: 38/125
request status: 28/30 (7 seconds remaining)
progress: 39/125
request status: 27/30 (4 seconds remaining)
progress: 40/125
request status: 26/30 (1 seconds remaining)
progress: 41/125
request status: 29/30 (10 seconds remaining)
progress: 42/125
request status: 28/30 (7 seconds remaining)
progress: 43/125
request status: 27/30 (5 seconds remaining)
progress: 44/125
request status: 26/30 (1 seconds remaining)
progress: 45/125
request status: 29/30 (10 seconds remaining)
progress: 46/125
request status: 28/30 (7 seconds remaining)
progress: 47/125
request status: 27/30 (4 seconds remaining)
progress: 48/125
request status: 26/30 (1 seconds remaining)
progress: 49/125
request status: 29/30 (10 seconds remaining)
progress: 50/125
request status: 28/30 (7 seconds remaining)
progress: 51/125
request status: 27/30 (4 seconds remaining)
progress: 52/125
request status: 26/30 (1 seconds remaining)
progress: 53/125
request status: 29/30 (10 seconds remaining)
progress: 54/125
request status: 28/30 (7 seconds remaining)
progress: 55/125
request status: 27/30 (4 seconds remaining)
progress: 56/125
request status: 26/30 (1 seconds remaining)
progress: 57/125
request status: 29/30 (10 seconds remaining)
progress: 58/125
request status: 28/30 (6 seconds remaining)
progress: 59/125
request status: 27/30 (3 seconds remaining)
progress: 60/125
request status: 29/30 (10 seconds remaining)
progress: 61/125
request status: 28/30 (6 seconds remaining)
progress: 62/125
request status: 27/30 (2 seconds remaining)
progress: 63/125
request status: 29/30 (10 seconds remaining)
progress: 64/125
request status: 28/30 (6 seconds remaining)
progress: 65/125
request status: 27/30 (2 seconds remaining)
progress: 66/125
request status: 29/30 (10 seconds remaining)
progress: 67/125
request status: 28/30 (6 seconds remaining)
progress: 68/125
request status: 27/30 (3 seconds remaining)
progress: 69/125
request status: 29/30 (10 seconds remaining)
progress: 70/125
request status: 28/30 (7 seconds remaining)
progress: 71/125
request status: 27/30 (4 seconds remaining)
progress: 72/125
request status: 26/30 (1 seconds remaining)
progress: 73/125
request status: 29/30 (10 seconds remaining)
progress: 74/125
request status: 28/30 (7 seconds remaining)
progress: 75/125
request status: 27/30 (4 seconds remaining)
progress: 76/125
request status: 26/30 (0 seconds remaining)
progress: 77/125
request status: 29/30 (10 seconds remaining)
progress: 78/125
request status: 28/30 (7 seconds remaining)
progress: 79/125
request status: 27/30 (4 seconds remaining)
progress: 80/125
request status: 26/30 (0 seconds remaining)
progress: 81/125
request status: 29/30 (10 seconds remaining)
progress: 82/125
request status: 28/30 (7 seconds remaining)
progress: 83/125
request status: 27/30 (3 seconds remaining)
progress: 84/125
request status: 26/30 (0 seconds remaining)
progress: 85/125
request status: 29/30 (10 seconds remaining)
progress: 86/125
request status: 28/30 (7 seconds remaining)
progress: 87/125
request status: 27/30 (3 seconds remaining)
progress: 88/125
request status: 26/30 (0 seconds remaining)
progress: 89/125
request status: 29/30 (10 seconds remaining)
progress: 90/125
request status: 28/30 (7 seconds remaining)
progress: 91/125
request status: 27/30 (4 seconds remaining)
progress: 92/125
request status: 29/30 (10 seconds remaining)
progress: 93/125
request status: 28/30 (7 seconds remaining)
progress: 94/125
request status: 27/30 (4 seconds remaining)
progress: 95/125
request status: 26/30 (1 seconds remaining)
progress: 96/125
request status: 29/30 (10 seconds remaining)
progress: 97/125
request status: 28/30 (7 seconds remaining)
progress: 98/125
request status: 27/30 (4 seconds remaining)
progress: 99/125
request status: 26/30 (0 seconds remaining)
progress: 100/125
request status: 29/30 (10 seconds remaining)
progress: 101/125
request status: 28/30 (7 seconds remaining)
progress: 102/125
request status: 27/30 (4 seconds remaining)
progress: 103/125
request status: 26/30 (0 seconds remaining)
progress: 104/125
request status: 29/30 (10 seconds remaining)
progress: 105/125
request status: 28/30 (7 seconds remaining)
progress: 106/125
request status: 27/30 (4 seconds remaining)
progress: 107/125
request status: 26/30 (1 seconds remaining)
progress: 108/125
request status: 29/30 (10 seconds remaining)
progress: 109/125
request status: 28/30 (7 seconds remaining)
progress: 110/125
request status: 27/30 (3 seconds remaining)
progress: 111/125
request status: 26/30 (0 seconds remaining)
progress: 112/125
request status: 29/30 (10 seconds remaining)
progress: 113/125
request status: 28/30 (7 seconds remaining)
progress: 114/125
request status: 27/30 (3 seconds remaining)
progress: 115/125
request status: 26/30 (0 seconds remaining)
progress: 116/125
request status: 29/30 (10 seconds remaining)
progress: 117/125
request status: 28/30 (7 seconds remaining)
progress: 118/125
request status: 27/30 (4 seconds remaining)
progress: 119/125
request status: 26/30 (0 seconds remaining)
progress: 120/125
request status: 29/30 (10 seconds remaining)
progress: 121/125
request status: 28/30 (7 seconds remaining)
progress: 122/125
request status: 27/30 (4 seconds remaining)
progress: 123/125
request status: 26/30 (1 seconds remaining)
progress: 124/125
request status: 29/30 (10 seconds remaining)
progress: 125/125
request status: 28/30 (7 seconds remaining)
fetching complete

In [35]:
df["state"] = df["state"].replace("DC", 1)
df["state"] = df["state"].replace("MD", 2)
df["state"] = df["state"].replace("VA", 3)

for index,row in df.iterrows():
    if df.loc[index, "state"] != 1 and df.loc[index, "state"] != 2 and df.loc[index, "state"] != 3:
        df.loc[index, "state"] = 4

In [40]:
print(df)

                              name        uid  state            city     lon  \
0                         BlueCart  197688146      1      Washington  -77.04
1                       Les Turner  208042831      3    Falls Church  -77.17
2                   michael murphy  197252012      2   Silver Spring  -77.05
3                            -----  221621957      1      Washington  -77.00
4                                .   92532152      4   Beverly Hills -118.41
5                                .  160618112      4       Anchorage -149.75
6                                .  182982506      1      Washington  -77.07
7                 'Boomie' Odumade   11937329      2          Lanham  -76.85
8                          'Jose l   11054609      1      Washington  -77.02
9                             (AW)  240554231      1      Washington  -77.02
10                         (Gazan)  195350930      2       Rockville  -77.17
11                     @ac7ionabl3   13184811      4   San Francisco -122.44
12                   @ROYCEDARULER  222526709      1      Washington  -76.93
13                         1235dsh  222587617      3    Falls Church  -77.17
14                          247101  183150828      3     Centreville  -77.47
15     3Si Microventure & Holdings  195212767      3          Vienna  -77.26
16                              54  260562514      2        Bethesda  -77.10
17                       703toyota  183264647      3    Mount Vernon  -77.11
18                           70909  113149032      4           Mango    0.45
19                               A  210503877      4      Bellingham -122.44
20                               A   41459102      2        La Plata  -76.97
21                               A  219816903      1      Washington  -77.02
22                             A B  243220615      1      Washington  -77.02
23                             A C  182685097      3       Arlington  -77.06
24                             A C  242625438      1      Washington  -77.03
25                          A Faye  231407744      2   Silver Spring  -77.01
26                          A Khan  235292309      1      Washington  -76.99
27                 A Meetup Member  191842778      3       Arlington  -77.09
28                        A Mistry  170944422      1      Washington  -77.04
29                          A Soni    5680694      1      Washington  -77.02
...                            ...        ...    ...             ...     ...
24867                 Zubair Talib   14139761      1      Washington  -77.04
24868                        Zubin   76215712      4   San Francisco -122.42
24869                   Zufan Meka  230776078      4  Lafayette Hill  -75.25
24870                Zuheir Sharif  189565926      1      Washington  -77.04
24871                Zuly Gonzalez   74154862      2       Baltimore  -76.64
24872                        Zulya  185039838      2       Greenbelt  -76.88
24873                         Zuri  110557212      1      Washington  -77.04
24874                     Zvi Band    8451766      1      Washington  -77.02
24875                Zvika Krieger   45959872      1      Washington  -77.04
24876                   Zzertdw Ca  263975623      1      Washington  -77.02
24877                Будагчин Эрка  230077326      3       Arlington  -77.10
24878                         кαηu  197002085      1      Washington  -77.02
24879               Митко Геренски   57994832      1      Washington  -77.06
24880                   Сигма Трон  106932462      4         Oakland -122.27
24881                 Тимур Чмерук  217461834      1      Washington  -77.03
24882                      ქιτεиdд  237317324      2        Columbia  -76.85
24883                  عطيه الغروي  248174788      4          Riyadh   46.77
24884          ‫فروشگاه جورواجور‬‎  206064479      4          Tehran   51.43
24885            አልአዛር ግርማ ኃይለማርያም  162950092      3         Fairfax  -77.37
24886                  የኔወርቅ አንዳርጌ  222781236      1      Washington  -77.03
24887                      ਨੀਰ ਤਾਨ  230902058      4         Atlanta  -84.36
24888                           乔治  197940256      4         Absecon  -74.50
24889                          全鑫子  215814515      3       Arlington  -77.07
24890                           明陈  267043454      1      Washington  -77.03
24891                        若林 敬之   80419522      2       Rockville  -77.15
24892                          김종혁  208791055      3          Vienna  -77.26
24893                          김준기  260164661      1      Washington  -76.99
24894                          임영규  228511671      3       Arlington  -77.10
24895                          전준하  184015390      1      Washington  -77.06
24896                          현종석  215721600      4           Seoul  126.99

         lat
0      38.92
1      38.89
2      39.04
3      38.89
4      34.10
5      61.20
6      38.91
7      38.96
8      38.88
9      38.91
10     39.09
11     37.80
12     38.84
13     38.88
14     38.82
15     38.90
16     38.98
17     38.72
18     10.35
19     48.76
20     38.52
21     38.91
22     38.91
23     38.86
24     38.93
25     39.02
26     38.90
27     38.90
28     38.91
29     38.91
...      ...
24867  38.91
24868  37.78
24869  40.09
24870  38.91
24871  39.33
24872  39.00
24873  38.91
24874  38.91
24875  38.91
24876  38.91
24877  38.89
24878  38.91
24879  38.94
24880  37.81
24881  38.90
24882  39.17
24883  24.65
24884  35.67
24885  38.86
24886  38.95
24887  33.85
24888  39.42
24889  38.89
24890  38.91
24891  39.08
24892  38.90
24893  38.91
24894  38.89
24895  38.94
24896  37.56

[24897 rows x 6 columns]

In [23]:
def scrapeData(protocol, host, resource):
    '''
    This function takes elements of a URL and returns the raw text from
    the webpage.
    Parameters: protocol, host, resource
    Returns: response text
    '''
    template = "{}://{}{}"
    url = template.format(protocol, host, resource)
    resp = requests.get(url)
    if resp.status_code == 200:
        return resp.text
    print("Error")

txt = scrapeData("https", "en.wikipedia.org", "/wiki/Washington_metropolitan_area")

In [24]:
def extractSectionBetween(txt, start, end):
    '''
    Slices text by substring boundaries rather than index boundaries.
    Parameters: text to slice, start string, end string
    Returns: trimmed string
    '''
    startInd = txt.find(start)
    endInd = txt.find(end)
    return txt[startInd:endInd]

txt = extractSectionBetween(txt, "92.3 years", "The Washington, D.C. area has the largest science")

In [25]:
def recreateTable(txt):
    '''
    Takes text containing a table in raw HTML format and
    places desired data in a pandas data frame.
    Parameters: html text
    Returns: pandas data frame
    '''
    pat = re.compile(r"<td><a .*?>(?P<county>.*?)<\/a>\n<\/td>\n<td .*?>(?P<pop>.*?)\n<\/td>")
    countyid = []
    i = 1
    county = []
    state = []
    pop = []
    for m in pat.finditer(txt):
        county.append(m["county"].split(",")[0].strip())
        state.append(m["county"].split(",")[1].strip())
        pop.append(int(m["pop"].replace(",", "")))
        countyid.append(i)
        i += 1
    return pd.DataFrame({"CountyID":countyid, "County":county, "State":state, "Population":pop})
    
popTable = recreateTable(txt)

popTable["State"] = popTable["State"].replace("D.C.", 1)
popTable["State"] = popTable["State"].replace("Maryland", 2)
popTable["State"] = popTable["State"].replace("Virginia", 3)



print(popTable)

    CountyID                  County  State  Population
0          1              Washington      1      681170
1          2          Calvert County      2       91251
2          3          Charles County      2      157705
3          4        Frederick County      2      247591
4          5       Montgomery County      2     1043863
5          6  Prince George's County      2      908049
6          7              Alexandria      3      155810
7          8        Arlington County      3      230050
8          9           Clarke County      3       14374
9         10         Culpeper County      3       50083
10        11          Fairfax County      3     1138652
11        12            Fairfax City      3       24164
12        13            Falls Church      3       14014
13        14         Fauquier County      3       69069
14        15          Fredericksburg      3       28297
15        16          Loudoun County      3      385945
16        17                Manassas      3       41483
17        18           Manassas Park      3       15915
18        19   Prince William County      3      455210
19        20     Rappahannock County      3        7388
20        21     Spotsylvania County      3      132010
21        22         Stafford County      3      144361
22        23           Warren County      3       39155

In [42]:
def getCreds(filename,subset,defaults={}):
    '''
    This function helps us connect to a database on hadoop2.  The
    userid password information is stored in a local file encoded
    in json format.  
    Parameters:
    filename is where json encoded userid/password information stored
    subset: dictionary key in json file
    defaults: alternative way to connect to database
    Returns: subdictionary based on subset parameter.
    '''
    try:
        with open(filename,'r') as file:
            D = json.load(file)
            file.close()
            if D[subset]:
                return D[subset]
            else:
                return defaults
    except:
        return defaults

def db_setup(userid,password):
    '''
    This function connects us to a database using our login credentials. 
    Paramters:
    userid - string with our userid
    password - string with our password
    database - string with database name
    Returns:
    SQL engine and SQL connection objects
    '''
    template = 'mysql+mysqlconnector://{}:{}@hadoop2.mathsci.denison.edu/'
    cstring = template.format(userid,password)
    engine = sa.create_engine(cstring)
    connection = engine.connect()
    
    return engine, connection

creds = getCreds('creds.json','mysql',defaults = {'user':'studen_j1', 'password':'studen_j1'})
creds

{'user': 'brown_b1', 'password': 'brown_b1'}

In [43]:
try:
    connection.close()
    del engine
except:
    pass
engine, connection = db_setup(creds['user'],creds['password'])

In [44]:
makeDB = "CREATE DATABASE brown_b1;"
connection.execute("commit")
connection.execute(makeDB)

In [45]:
def db_setup(userid,password, database):
    '''
    This function connects us to a database using our login credentials. 
    Paramters:
    userid - string with our userid
    password - string with our password
    database - string with database name
    Returns:
    SQL engine and SQL connection objects
    '''
    template = 'mysql+mysqlconnector://{}:{}@hadoop2.mathsci.denison.edu/{}'
    cstring = template.format(userid,password,database)
    engine = sa.create_engine(cstring)
    connection = engine.connect()
    
    return engine, connection

try:
    connection.close()
    del engine
except:
    pass
engine, connection = db_setup(creds['user'],creds['password'], "brown_b1")

In [49]:


makeCountyPopulations = "CREATE TABLE CountyPopulations(\
CountyID INT NOT NULL,\
CountyName VARCHAR(30),\
StateID INT,\
Population INT,\
PRIMARY KEY(CountyID)\
);"

makeStates = "CREATE TABLE States(\
StateID INT NOT NULL,\
State VARCHAR(30),\
PRIMARY KEY(StateID)\
);"

makeUsers = "CREATE TABLE Users(\
MemberID INT NOT NULL,\
Nickname VARCHAR(30),\
StateID INT,\
UserCity VARCHAR(30),\
UserLongitude DECIMAL(5, 2),\
UserLatitude DECIMAL(5, 2),\
PRIMARY KEY(MemberID)\
);"

#connection.execute(makeCountyPopulations)
#connection.execute(makeStates)
connection.execute(makeUsers)

In [50]:
countyRowTemplate = "INSERT INTO CountyPopulations\
(CountyID, CountyName, StateID, Population)\
VALUES({},{},{},{});"

stateRows = "INSERT INTO States\
(StateID, State)\
VALUES(1,'DC'),(2, 'Maryland'),(3,'Virginia'),(4,'OtherState');"

usersRowTemplate = "INSERT INTO Users\
(MemberID, Nickname, StateID, UserCity, UserLongitude, UserLatitude)\
VALUES({},{},{},{},{},{});"

#connection.execute(stateRows)


# for i in range(len(popTable)):
#     countyRow = countyRowTemplate.format(popTable.iloc[i, 0], "'"+popTable.iloc[i, 1].replace("'", "")+"'", popTable.iloc[i, 2], popTable.iloc[i, 3])
#     connection.execute(countyRow)
    

    
for i in range(len(df)):
    if i % 1000 == 0:
        print(i)
    usersRow = usersRowTemplate.format(df.iloc[i,1], "'"+df.iloc[i, 0].replace("'", "").replace("\\", "")+"'", df.iloc[i, 2], "'"+df.iloc[i, 3].replace("'", "")+"'", df.iloc[i, 4], df.iloc[i, 5])
    connection.execute(usersRow)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000

In [48]:
len(df)

24897

In [41]:
try:
    connection.close()
    del engine
    print("Connection closed")
except:
    pass
    print("No connection")

Connection closed